FE React was added
IF-115-Ruby/OSBB pull request #103
Opened 2020-11-17 13:09 UTC by Axedez

[Trello Task](https://trello.com/_____)

**CHECK LIST**
- [ ] specs added
- [ ] specs passed
- [ ] code coverage >90%
- [ ] DB indexes added if needed
- [ ] seed.rb file is updated if needed
- [ ] PR is reviewed manually again (to make sure you have 100% ready code)
- [ ] PR doesn't have conflicts with main branch
- [ ] I've checked new feature as logged in and logged out user if needed
- [ ] "let!" is used in specs
- [ ] screenshot of feature is added if task has UI

2020-11-17 13:16 UTC, sviatoslav-krupa requested changes

2020-11-17 13:16 UTC, sviatoslav-krupa commented on spec/requests/react_test_request_spec.rb
> +
remove that empty line

2020-11-17 13:16 UTC, sviatoslav-krupa commented on app/javascript/packs/reactrailsujs.js
> +ReactRailsUJS.useContext(componentRequireContext);
add new line

2020-11-17 13:16 UTC, sviatoslav-krupa commented on app/javascript/components/App.js
> +export default App
```suggestion
import React, {Component} from 'react';

class App extends Component {
  render () {
    return (
      <div>
        <h1>Test React App</h1>
        <p>Hello world!</p>
      </div>
    );
  }
}

export default App;
```
Always put `;` at the end of each line.

2020-11-17 14:55 UTC, marikrebega commented on Gemfile
> +gem 'react-rails'
please add gem version

2020-11-17 20:10 UTC, Andrii-Kozak approved these changes

2020-11-18 05:29 UTC, mmarusyk approved these changes

2020-11-18 09:35 UTC, chu4 approved these changes

2020-11-18 09:35 UTC, merged