Export pdf
IF-115-Ruby/OSBB pull request #67
Opened 2020-10-30 15:02 UTC by Axedez

[Trello Task](https://trello.com/_____)

**CHECK LIST**
- [ ] specs added
- [ ] specs passed
- [ ] code coverage >90%
- [ ] DB indexes added if needed
- [ ] seed.rb file is updated if needed
- [ ] PR is reviewed manually again (to make sure you have 100% ready code)
- [ ] PR doesn't have conflicts with main branch
- [ ] I've checked new feature as logged in and logged out user if needed
- [ ] "let!" is used in specs
- [ ] screenshot of feature is added if task has UI

2020-10-30 15:07 UTC, sviatoslav-krupa requested changes

2020-10-30 15:07 UTC, sviatoslav-krupa commented on app/assets/stylesheets/receipt.scss
> +}
add new line

2020-10-30 15:07 UTC, sviatoslav-krupa commented on app/views/account/utility_providers/show.html.slim
> +  class: 'btn btn-info btn-custom'
add new line

2020-10-30 15:07 UTC, sviatoslav-krupa commented on app/views/shared/account/_header.html.slim
>                = t('.btn_destoy_auth')
add new line

2020-10-30 15:07 UTC, sviatoslav-krupa commented on app/controllers/application_controller.rb
> +  def set_locale
це відноситься до твоєї таски?

2020-10-30 15:07 UTC, sviatoslav-krupa commented on config/initializers/wicked_pdf.rb
> +WickedPdf.config = {
видали цей файл, він пустий

2020-10-30 15:07 UTC, sviatoslav-krupa commented on spec/controllers/home_controller_spec.rb
> +    subject { get :about }
чому ти це змінив?

2020-10-30 15:09 UTC, Axedez commented on app/controllers/application_controller.rb
> +  def set_locale
Це попередня таска, яка ще не змерджена

2020-10-30 15:10 UTC, Axedez commented on config/initializers/wicked_pdf.rb
> +WickedPdf.config = {
А якщо в майбутньому треба буде додати щось в конфіг? ЧИ в такому випадку просто створиться новий файл?

2020-10-30 15:16 UTC, Axedez commented on spec/controllers/home_controller_spec.rb
> +    subject { get :about }
Прочитав на стеку + мейт вище також написав сабджект

2020-10-30 15:17 UTC, Axedez commented on spec/controllers/home_controller_spec.rb
> +    subject { get :about }
Прочитав на стеку + мейт вище також написав сабджект

2020-11-02 10:13 UTC, pereslop commented on app/assets/stylesheets/receipt.scss
> +  border-bottom: 1px solid #eee;
Duplicated style

2020-11-02 10:13 UTC, pereslop commented on app/assets/stylesheets/receipt.scss
> +  .invoice-box table tr.information table td {
Dulicated style, the same as above, dry it

2020-11-02 10:13 UTC, pereslop commented on app/controllers/account/payments_controller.rb
> +  before_action :set_utility_providers
If you have only one action, you dont need it

2020-11-02 10:13 UTC, pereslop commented on app/views/account/payments/show.html.slim
> += link_to "Show PDF", [:account, :utility_provider, :payment, format: :pdf],
I18n

2020-11-02 10:13 UTC, pereslop commented on app/views/account/utility_providers/_utility_provider.html.slim
> +      method: :get
Do really need it?

2020-11-02 10:13 UTC, pereslop commented on config/routes.rb
> +        resources :payments, only: %i[show]
If you have only one action, you can just specify that one, you dont need recourses

2020-11-02 10:13 UTC, pereslop commented on spec/controllers/account/payments_controller_spec.rb
> +  let!(:utility_provider) { create(:billing_contract) }
Do you need to create  provider, if you dont check anything related to it in specs?

2020-11-05 19:06 UTC, matsevich approved these changes

2020-11-05 19:47 UTC, marikrebega approved these changes

2020-11-05 21:44 UTC, Ukhanskyi approved these changes

2020-11-06 08:24 UTC, BogdanBusko commented on app/assets/stylesheets/receipt.scss
> +$white-blur: #eee;
move to file colors

2020-11-06 08:24 UTC, BogdanBusko commented on app/controllers/account/payments_controller.rb
> +    @utility_provider = current_user.billing_contracts.find_by id: params[:id]
enter after

2020-11-06 08:25 UTC, BogdanBusko commented on app/controllers/account/payments_controller.rb
> +      flash.now[:alert] = 'Contract not found!'
mb you should have some redirect here

2020-11-06 08:26 UTC, BogdanBusko commented on app/views/layouts/receipt_pdf.html.slim
> +      = yield
remove 2 spaces before =

2020-11-06 08:27 UTC, BogdanBusko commented on spec/controllers/account/payments_controller_spec.rb
> +  before { sign_in user }
mb you have some helper for this code? controller_macros

2020-11-06 15:14 UTC, chu4 approved these changes

2020-11-06 15:15 UTC, merged